name: Periodic Health Check

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: health check of deployed add
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-w0vx.onrender.com/health
          max-attemps: 3
          retry-delay: 5s
