name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.MY_RENDER_SERVICE_ID }}?key=${{ secrets.MY_RENDER_API_KEY }}
      - name: Discord webhook success notification
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          text: A new version of Pokedex deployed
          description: 'https://full-stack-open-pokedex-w0vx.onrender.com/ by Nagendra'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord webhook failure notification
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          description: ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.name }} build broken ☹️
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        uses: anothrNick/github-tag-action@93b75ef5a57640183b7e69a77098f41184b2e8ad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
